name: GitHub Activity Bot
permissions:
  contents: write
on:
  schedule:
    - cron: '0 10 * * *'  # Run once daily at 10:00 UTC to reduce noise
  workflow_dispatch:  # Allow manual execution
jobs:
  activity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Bot"
        
    - name: Generate Activity
      run: python generate_activity.py
        
    - name: Commit and Push Changes
      run: |
        git add .
        if git diff --cached --quiet; then
